apiVersion: v1
kind: Deployment
metadata:
  name: victory-royale
spec:
  replicas: 1
    spec:
      containers:
        - image: wil42/playground:v1
          name: victory-royale
      ports:
        - containerPort: 8888
          name: http
          protocol: TCP