apiVersion: v1
kind: Ingress
metadata:
  name: victory-royale-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: victory-royale
            port:
              number: 8888